Feat/rag notification
FLock-io/interface pull request #139
Opened 2023-12-04 10:17 UTC by elihylui

2023-12-04 12:45 UTC, rodrigopavezi submitted a review, later dismissed

2023-12-04 19:45 UTC, rodrigopavezi commented on src/pages/api/postCourierUser.ts
> +            method: 'POST',
@elihylui also make sure the address is lower case when sending to courier.

2023-12-06 12:33 UTC, rodrigopavezi requested changes

2023-12-06 12:33 UTC, rodrigopavezi commented on src/pages/_app.tsx
> +        {/* <Notification> */}
@elihylui notification should be here as it will be needed when user is in any page of the app.

I suggest you create a context in the Notification component so it will set a state variable you can get the message in any Component then.

2023-12-06 16:00 UTC, MIDAV0 approved these changes

2023-12-06 16:05 UTC, merged