Feat/claim nft
FLock-io/interface pull request #91
Opened 2023-10-30 16:18 UTC by elihylui

This PR:
- adds a section to show which NFT has been minted for user

2023-10-30 18:04 UTC, MIDAV0 approved these changes
Looks good

2023-10-31 10:34 UTC, rodrigopavezi requested changes
@elihylui could add it to a env var?

2023-10-31 18:02 UTC, rodrigopavezi requested changes

2023-10-31 18:02 UTC, rodrigopavezi commented on src/pages/gptResearcher.tsx
> +      const ws_uri = `ws://${process.env.RESEARCHER_WEB_SOCKET_URL}?token=${userToken}&authKey=${publicKey}`
@elihylui the value in the env var should include the procotol, such as `wss://` so like this
RESEARCHER_WEB_SOCKET_URL=wss://researcher.flock.io

2023-10-31 18:11 UTC, rodrigopavezi approved these changes

2023-11-01 10:36 UTC, merged